apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mobileclients.mdc.aerogear.org
spec:
  group: mdc.aerogear.org
  version: v1alpha1
  scope: Namespaced
  names:
    plural: mobileclients
    singular: mobileclient
    kind: MobileClient
    shortNames:
    - mc
  validation:
    # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      properties:
        spec:
          properties:
            apiKey:
              type: string
              pattern: '(\w{8}-\w{4}-\w{4}-\w{4}-\w{11})'
            # `spec.name` is used in OpenShift as the descriptor title of the custom resource
            name:
              type: string
              pattern: '([\w-])'
            dmzUrl:
              type: string
              nullable: true
